function [ret] = inc_elast_credit_fn(b0, data_mat)

  ret = logitcdf_fn(mean(data_mat(:, 2:end)) * b0) * ...
    ( 1 - logitcdf_fn(mean(data_mat(:, 2:end)) * b0) ) * ...
    b0(4)  * ...
    mean(data_mat(:, 5)) / logitcdf_fn(mean(data_mat(:, 2:end)) * b0);
  
end