function ret = consump_model_fn( betas, x)
  ret = betas(1) + betas(2) .* x(:, 2) - ...
    betas(3) .* ( x(:, 3) + betas(1) + ...
    betas(2) .* x(:, 4) ) - ...
    betas(4) .* ( x(:, 5) + betas(1) + ...
    betas(2) .* x(:, 6) ) ;
end
