function ret = consump_model_fn( betas, x)
  ret = betas(1) + betas(2) .* x(:, strcmp(varnames,'INC')) - ...
    betas(3) .* ( x(:, strcmp(varnames,'CONSUME_L1')) + betas(1) + ...
    betas(2) .* x(:, strcmp(varnames,'INC_L1')) ) - ...
    betas(4) .* ( x(:, strcmp(varnames,'CONSUME_L2')) + betas(1) + ...
    betas(2) .* x(:, strcmp(varnames,'INC_L2')) ) 
end
